### ISSUE TITLE
DimStorage owner breaks with colors

### ISSUE THREAD

**Issue by Yamza** [Edivad99/DimStorage#11]
When setting owner on the chest it seems to be including any name color with the name, so if a players name color changes they will no longer have access to the chest.
https://i.imgur.com/gzwx8zc.gifv

**Comment by Edivad99** [comment]
Hi, I already have a solution ready for this bug. How do you change the color of the name?

**Comment by Yamza** [comment]
Currently using this mod https://www.curseforge.com/minecraft/mc-mods/colouredchat
Sounds like the issue might be that it's setting players into fake teams and not the color itself?

**Comment by uberifix** [comment]
The problem is with using display names as a reference to a player. This can change with players changing their minecraft name or if any mod or minecraft itself modifies the display name. (In this issue minecraft itself is changing the display name of players in teams with a team colour) 

https://github.com/Edivad99/DimStorage/blob/1.15.x/src/main/java/edivad/dimstorage/tile/TileFrequencyOwner.java#L44
https://github.com/Edivad99/DimStorage/blob/ca5edda965bc671a6c976d521f608656027ed216/src/main/java/edivad/dimstorage/api/Frequency.java#L152

These should all be changed to save the players uuid instead and only get the display name when you display the players name in guis

**Comment by Edivad99** [comment]
In fact, I solved it this way

**Comment by Edivad99** [comment]
When the update comes out, before updating you must move all the inventory you had to the private part, to the public part. This is due to the change of the key system useful for saving the contents of the chest. When the update comes out, I will also inform you via the minecraft terminal.
