### ISSUE TITLE
[1.15.2] Can't remove items from RS grid when connected to DimStorage chest

### ISSUE THREAD

**Issue by ocram9** [Edivad99/DimStorage#27]
**Describe the bug**
When I connect an external storage to a Dimensional Storage chest I can't use the Refined Storage grid anymore (as in I can't remove any items). I'm not sure if this is an issue with this mod or Refined Storage but I decided to report it here first. The chest is set to public and not locked.

**Configuration**
Mod version: 3.1.5
Forge version: 31.2.5
Minecraft version: 1.15.2
Are you playing on server?: Yes

**To Reproduce**
1. Place a DimStorage chest
2. Connect a Refined Storage external storage to the chest
3. Open the Refined Storage grid and try to remove items (if you click fast enough you can remove an item once but after that it doesn't work anymore).

**Expected behavior**
Being able to connect a Refined Storage external storage and still being able to access the Refined Storage grid.

**Comment by Edivad99** [comment]
I'm not sure it's my bug. As you can see the items you should also be able to take them.

**Comment by ocram9** [comment]
I don't know which mod is causing this. The only thing I know is that when I connect a dimstorage chest I can't take any items. Not just the items that are in the chest.

**Comment by Edivad99** [comment]
I have done other tests, I advise you to report the problem to the Refined Storage'guys

**Comment by Darkere** [comment]
This issue is caused by this code here: 
https://github.com/Edivad99/DimStorage/blob/764fd4b53b0681ad86be01b734d7dacac0b395bc/src/main/java/edivad/dimstorage/tile/TileEntityDimChest.java#L87

You are calling `notifyNeighborsOfStateChange` every second. Even if nothing has changed. I myself am not exactly sure when it should be called but that seems excessive :).

RS cannot (due to performance issues) update the grid every time a state change happens and as such this creates a desync between the items shown and the items the external storage is reading.

**Comment by Edivad99** [comment]
That line is right, because in this way the dimchest updates at most every second. If I have two dimchest A and B with the same frequency and A modifies the content inside, B must update and update its neighbors.
At the moment I am very busy with the uni exams. As soon as I finish I try to take a look at it to see if it is possible to fix it, also I tried to see and the EnderStorge also has the same problem.
@ocram9, for now use an import bus and it should work.
